export const MENUS = [
  { label: "Air Quality", value: "air pollution", path: "/" },
  { label: "Weather info", value: "temprature", path: "/weather" },
  // { label: "Water Pollution", value: "water pollution", path: "/2" },
  // { label: "Heat Wave", value: "head wave", path: "/3" },
];

export const LOGO =
  "https://i.pinimg.com/originals/f3/7e/bb/f37ebbea1f4318dec775a4d705bd7cca.gif";

export const navLinks = (pathname) => {
  if (pathname === "/") {
    return "Air Quality";
  } else if (pathname === "/weather") {
    return "Weather info";
  } else {
    return "Not found";
  }
};

export const BASEMAP = [
  {
    name: "cadastre satellite",
    mapLink:
      "https://api.maptiler.com/maps/cadastre-satellite/style.json?key=yu7UtJN0eOg536ACtL8z",
    IMGlink:
      "https://res.cloudinary.com/dhqxln7zi/image/upload/v1690649710/Screenshot_2023-07-29_at_12.58.40_PM_ac5dpf.png",
  },
  {
    name: "basic",
    mapLink:
      "https://api.maptiler.com/maps/basic-v2/style.json?key=yu7UtJN0eOg536ACtL8z",
    IMGlink:
      "https://res.cloudinary.com/dhqxln7zi/image/upload/v1690651342/Screenshot_2023-07-29_at_10.51.58_PM_udd93p.png",
  },
  {
    name: "satellite",
    mapLink:
      "https://api.maptiler.com/maps/satellite/style.json?key=yu7UtJN0eOg536ACtL8z",
    IMGlink:
      "https://res.cloudinary.com/dhqxln7zi/image/upload/v1690649710/Screenshot_2023-07-29_at_12.57.46_PM_debsxd.png",
  },
  {
    name: "topo",
    mapLink:
      "https://api.maptiler.com/maps/topo-v2/style.json?key=yu7UtJN0eOg536ACtL8z",
    IMGlink:
      "https://res.cloudinary.com/dhqxln7zi/image/upload/v1690651459/Screenshot_2023-07-29_at_10.54.06_PM_nt90mq.png",
  },
  {
    name: "streets",
    mapLink:
      "https://api.maptiler.com/maps/streets-v2/style.json?key=yu7UtJN0eOg536ACtL8z",
    IMGlink:
      "https://res.cloudinary.com/dhqxln7zi/image/upload/v1690649709/Screenshot_2023-07-29_at_12.59.18_PM_y5iwqu.png",
  },
];

export const PIECHART_AVAILABLE = ["/"];
export const GRAPH_AVAILABLE = ["/"];
export const CITY_LIST_AVAILABLE = ["/weather"]
export const COLORS = [
  "#279EFF",
  "#7091F5",
  "#FF6969",
  "#9EB384",
  "#765827",
  "#FEBBCC",
  "#F11A7B",
  "#B70404",
];


export const country_list = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua &amp; Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia &amp; Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre &amp; Miquelon",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts &amp; Nevis",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad &amp; Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks &amp; Caicos",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
